#!/bin/bash

NEWORK_DIR=$PWD/..
WORKING_DIR=$PWD/../..
FABRIC_DIR=$WORKING_DIR/fabric-binary
COMPOSE_DIR=$NEWORK_DIR/compose
ORGANIZATIONS_DIR=$NEWORK_DIR/organizations
FABRIC_CA_DIR=$NEWORK_DIR/fabric-ca
export PATH=$PATH:$FABRIC_DIR/bin